export const INDEX_INVESTMENTS = 'INDEX_INVESTMENTS';
export const SHOW_INVESTMENT = 'SHOW_INVESTMENT';
export const ADD_INVESTMENT = 'ADD_INVESTMENT';
export const UPDATE_INVESTMENT = 'UPDATE_INVESTMENT';
export const DELETE_INVESTMENT = 'DELETE_INVESTMENT';
