export const INDEX_INVESTMENTS = 'INDEX_INVESTMENTS';
export const CREATE_INVESTMENT = 'CREATE_INVESTMENT';
export const UPDATE_INVESTMENT = 'UPDATE_INVESTMENT';
export const DELETE_INVESTMENT = 'DELETE_INVESTMENT';
